version: "3.9"
services:
  temperature_mock:
    build: .
    container_name: fastapi_publisher
    ports:
      - "4006:8000"
    environment:
      RABBITMQ_HOST: amqp://user:pass@host.docker.internal:5672/
      QUEUE_NAME: injector_queue
