services:
  yolo-service:
    build: .
    container_name: yolo_service
    networks:
      - app-network
    environment:
      - PORT=7676
    ports:
      - "${YOLO_PORT}:${YOLO_PORT}"
networks:
  app-network:
    driver: bridge
